# 数値計算  
- **Submission date**: 2017/10/06  
- **Team**: へび  
- **Members**:  
    + #5531 Akihiro Nitta  
    + #5557 Yuki Kotakehara  
    + #5501 Kazunori Sakai  

## モジュールの読み込み  
- [NumPy](http://www.numpy.org) is the main package for scientific computing with Python.  

In [1]:
import numpy as np

## 2.2.4 課題  p. 14
1. printfを使って次のように表示せよ.  
   i) Hello world.  ii) 1+1=2  
1. 次の数を順に表示せよ．  
    i)1から5までの整数．  
    ii) 5から1までの整数.  
    iii) 1から10にある偶数．  
1. 9x9表を作れ．  
1. 1 から 5 までの和を求めよ.  
1. nを5にして，n!=n×(n−1)×(n−2)⋯3×2×1n!=n×(n−1)×(n−1)⋯3×2×1を求めよ.  

In [2]:
# 1. 
# i)
print('Hello world')
# ii)
print('1+1=2')

Hello world
1+1=2


In [3]:
# 2.
# i)
print('i)')
for i in range(1, 5+1):
    print(i, end=' ')
# ii)
print('\nii)')
for i in reversed(range(1, 5+1)):
    print(str(i), end=' ')
# iii)
print('\niii)')
for i in range(1, 10+1):
    if i % 2 == 0:
        print(i, end=' ')

i)
1 2 3 4 5 
ii)
5 4 3 2 1 
iii)
2 4 6 8 10 

In [4]:
# 3.
for i in range(1, 10):
    for j in range(1, 10):
        print(str(i*j), end=' ')
    print('')

1 2 3 4 5 6 7 8 9 
2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


In [5]:
# 4.
sum = 0
for i in range(1, 6):
    sum = sum + i
print('sum = ' + str(sum))

sum = 15


In [6]:
# 5.
n = 5
factorial = 1
for i in range(1, n+1):
    factorial = factorial * i
print(str(n) + '! = ' + str(factorial))

5! = 120


## 2.3.8 課題  p. 20  
1. 1から100までの整数のうち5個をランダムに含んだ配列を生成せよ．  
1. さいころを１００回振って，出た目１から６が何回出たかを表示せよ．  
1. コイン６枚を一度に投げて，表向きの枚数を数えるプログラムを書け．  
1. 0から9までの整数5個から5桁の整数を作れ．（１桁目が０になっても気にするな）  
1. 小数点以下8桁のそれぞれの桁の数を配列に格納せよ．  
1. 255以下の10進数をランダムに生成して，8桁の2進数へ変換せよ．  

In [7]:
# 1.
array = np.random.randint(1, 101, 5)
print(array)

[35 15 87 96 53]


In [8]:
# 2.
count = np.zeros(6)

for i in range(100):
    count[np.random.randint(0, 6)] += 1
    
print(count)

[ 12.  19.  20.  16.  16.  17.]


In [9]:
# 3.
coin = np.random.rand(6)
coin = coin>0.5
print(coin.sum())

3


In [10]:
# 4.
values = np.random.randint(0, 10, 5)
value = 0

for v in values:
    value *= 10
    value += v

print(values, value)


[3 0 9 3 0] 30930


In [11]:
# 5.
value = np.random.rand()
array = np.array([])

print(value)
for i in range(8):
    value = value - int(value)
    value = value*10
    array = np.append(array, int(value))

print(array)



0.9806237266570639
[ 9.  8.  0.  6.  2.  3.  7.  2.]


In [12]:
# 6.
value = np.random.randint(0, 256)
bin_value = bin(value)
print('value: ', value)
print('bin_value: ', bin_value)

value:  163
bin_value:  0b10100011


## 2.4.4 課題  p. 24  
1. 西暦を代入したら，明治，大正，昭和，平成で答えてくれるプログラムを作成せよ．西暦1868,1912,1926,1989年をそれぞれの元年とする．  
1. 整数を代入したら，それ以下の素数をすべて表示するプログラムを作れ．素数かどうかの判定はMapleコマンドのisprimeを用いよ．  
1. pが素数でp+2も素数のとき，これらは双子の素数と呼ばれる．10以上，100以下の双子の素数を全部見つけて出力せよ．  
1. 素数判定を原理から実現せよ．ある数nが素数かどうか(自分自身の数nと1以外の数で割りきれないかどうか)を判定せよ．割り算の余り(剰余)はiremで求まる．  
    例えばとして変数residue(余りの英語)をprintfしてみよ．番兵を置いておいて，n­1から2までの数でnを次々と割っていき，一度でも割り切れれば番兵にマークをつける．ループが終わった後に番兵のマークを見て素数(prime number)かどうかを判定すればよい．
1. うるう年かどうかを表示するプログラムをかけ．
    うるう年は4で割り切れる数の年．ただし，100で割り切れる年はうるう年でなく，400で割り切れる年はうるう年．  
1. **ゴールドバッハの予想**  
    「6以上の偶数は二つの素数の和として表わされる」という予想を100以下の偶数について検証せよ．あらかじめ100までの素数をリストアップしておいてそのなかから組み合わせを探すと便利  

In [13]:
# 1.
year = int(input('year >>> '))
year_jp = 0

# 平成
if year >= 1989:
    year_jp = year - 1989 + 1
    print('平成' + str(year_jp) + '年')
# 昭和
elif year >= 1926:
    year_jp = year - 1926 + 1
    print('昭和' + str(year_jp) + '年')
# 大正
elif year >= 1912:
    year_jp = year - 1912 + 1
    print('大正' + str(year_jp) + '年')
# 明治
elif year >= 1868:
    year_jp = year - 1868 + 1
    print('明治' + str(year_jp) + '年')
# それ以外
else:
    print('unknown')

year >>> 1923
大正12年


In [14]:
# 2.
def isprime(num):
    '''
    Arguments:
    num -- 素数判定対象のint値
    
    Returns:
    True/False -- 素数であるか否か
    '''
    buff = num
    bool_prime = True
    for i in range(2, num):
        if buff % i == 0:
            bool_prime = False
            break
    return bool_prime

value = int(input('value > '))
print(isprime(value))

for i in range(2, value+1):
    if isprime(i):
        print(i)

value > 13
True
2
3
5
7
11
13


In [15]:
# 3.
for i in range(10, 100+1):
    if isprime(i) and isprime(i+2): # 2. で作成した関数 isprime を使用
        print(str(i) + ', ' + str(i+2))

11, 13
17, 19
29, 31
41, 43
59, 61
71, 73


In [16]:
# 4.
n = int(input("n > "))
bool_prime = True
for i in reversed(range(2, n)):
    residue = n%i
    print('{0} % {1} = {2}'.format(n, i, residue))
    if residue==0:
        bool_prime = False
        break
    
if bool_prime:
    print(n, "is a prime number.")
else:
    print(n, "is not a prime number.")


n > 13
13 % 12 = 1
13 % 11 = 2
13 % 10 = 3
13 % 9 = 4
13 % 8 = 5
13 % 7 = 6
13 % 6 = 1
13 % 5 = 3
13 % 4 = 1
13 % 3 = 1
13 % 2 = 1
13 is a prime number.


In [17]:
# 5.
year = int(input("year > "))

if year%400 == 0:
    print(year, "はうるう年")
elif year%100 == 0:
    print(year, "はうるう年でない")
elif year%4 == 0:
    print(year, "はうるう年")
else:
    print(year, "はうるう年でない")

year > 1922
1922 はうるう年でない


In [18]:
# 6.
def isprime(num):
    '''
    Arguments:
    num -- 素数判定対象のint値
    
    Returns:
    True/False -- 素数であるか否か
    '''
    buff = num
    bool_prime = True
    for i in range(2, num):
        if buff % i == 0:
            bool_prime = False
            break
    return bool_prime

list_prime = []
for i in range(2, 101):
    if isprime(i):
        list_prime.append(i)
        
print(list_prime)
        
for i in range(6, 101, 2):
    for j in range(len(list_prime)):
        for k in range(len(list_prime)):
            if(list_prime[j]+list_prime[k]>i):
                break
            elif(list_prime[j]+list_prime[k]==i):
                print('{0}={1}+{2}'.format(i, list_prime[j], list_prime[k]))
                break

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
6=3+3
8=3+5
8=5+3
10=3+7
10=5+5
10=7+3
12=5+7
12=7+5
14=3+11
14=7+7
14=11+3
16=3+13
16=5+11
16=11+5
16=13+3
18=5+13
18=7+11
18=11+7
18=13+5
20=3+17
20=7+13
20=13+7
20=17+3
22=3+19
22=5+17
22=11+11
22=17+5
22=19+3
24=5+19
24=7+17
24=11+13
24=13+11
24=17+7
24=19+5
26=3+23
26=7+19
26=13+13
26=19+7
26=23+3
28=5+23
28=11+17
28=17+11
28=23+5
30=7+23
30=11+19
30=13+17
30=17+13
30=19+11
30=23+7
32=3+29
32=13+19
32=19+13
32=29+3
34=3+31
34=5+29
34=11+23
34=17+17
34=23+11
34=29+5
34=31+3
36=5+31
36=7+29
36=13+23
36=17+19
36=19+17
36=23+13
36=29+7
36=31+5
38=7+31
38=19+19
38=31+7
40=3+37
40=11+29
40=17+23
40=23+17
40=29+11
40=37+3
42=5+37
42=11+31
42=13+29
42=19+23
42=23+19
42=29+13
42=31+11
42=37+5
44=3+41
44=7+37
44=13+31
44=31+13
44=37+7
44=41+3
46=3+43
46=5+41
46=17+29
46=23+23
46=29+17
46=41+5
46=43+3
48=5+43
48=7+41
48=11+37
48=17+31
48=19+29
48=29+19
48=31+17
48=37+11
48=41+7
48=43+5
50=3+47
50

## 2.4.5 課題  p. 29
1. **三角形の面積**  
    底辺と高さを引数として，面積を返す関数areaを作れ．  

1. **MyIsprime**  
    前章の課題４で求めた素数判定プログラムをprocにせよ．  

1. **ルートの距離二つの位置座標**  
    x1:=[0.0, 0.0] x2:=[1.0, 1.0]から距離を求めるMyDistance関数を作れ．次に，4つの位置座標 x[1]=[0.0, 0.0] x[2]=[1.0, 1.0] x[3]=[1.0, 0.0] x[4]=[0.0, 1.0] を読み込んで，座標順に[1,2,3,4,1]と巡る距離を求めよ．  

1. **最大数**  
    ランダムな整数が格納されたリストを受け取り，そのリスト中の最大数を返す関数MyMaxを作れ．1から100までのランダムな整数のリストは次のようにして作れる．  

In [19]:
# 1. 三角形の面積
def area(base, height):
    '''
    Arguments:
    base -- 三角形の底辺
    height -- 三角形の高さ
    
    Returns:
    三角形の面積
    '''
    return base*height/2.0

# 1. test
print('area: ' + str(area(10, 12)))

area: 60.0


In [20]:
# 2. MyIsPrime
def MyIsprime(num):
    '''
    Arguments:
    num --整数
    
    Returns:
    true or false
    '''
    bool_prime = True
    for i in reversed(range(2, num)):
        residue = num%i
        if residue==0:
            bool_prime = False
            break
    return bool_prime

# 2. test
num1= 41
num2 = 2
print('{0} : {1}'.format(num1, MyIsprime(num1)))
print('{0} : {1}'.format(num2, MyIsprime(num2)))
print('{0} : {1}'.format(num1*num2, MyIsprime(num1*num2)))

41 : True
2 : True
82 : False


In [21]:
# 3. ルートの距離2つの位置座標
def MyDistance(p1, p2):
    '''
    Arguments:
    p1, p2 -- 距離計算対象の2点
    
    Returns:
    2点間の距離
    '''
    p1 = np.array(p1)
    p2 = np.array(p2)
    return np.linalg.norm(p1-p2)

# 3. test
x = [[0.0, 0.0], [1.0, 1.0], [1.0, 0.0], [0.0, 1.0]]
print('x: ' + str(x))
x.append(x[0]) #x[4]=x[0]
print("x[0]{0}とx[1]{1}の距離は　".format(x[0], x[1]) +str(MyDistance(x[0], x[1])))

ans = 0
for i in range(0, 4):
    ans = ans + MyDistance(x[i], x[i+1])
    
print('{0}→{1}→{2}→{3}→{4} と巡る距離は　{5}'.format(x[0], x[1], x[2], x[3], x[4], ans))

x: [[0.0, 0.0], [1.0, 1.0], [1.0, 0.0], [0.0, 1.0]]
x[0][0.0, 0.0]とx[1][1.0, 1.0]の距離は　1.41421356237
[0.0, 0.0]→[1.0, 1.0]→[1.0, 0.0]→[0.0, 1.0]→[0.0, 0.0] と巡る距離は　4.82842712474619


In [22]:
# 4. 最大数
def MyMax(array):
    '''
    Arguments:
    array -- np.array配列（int）
    
    Returns:
    arrayの要素の最大値
    '''
    assert(array.dtype=='int64') # intかチェック
    return np.max(array)

# 4. test
array = np.random.randint(1, 100+1, 5)
print(array)
print(MyMax(array))

[31 47 56 74  9]
74
